import Head from "next/head";
import Login from "../components/Section/Login";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Footy Tips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section">
          <div className="container">
            <div className="hero | u-bg-white-0 u-mx-auto u-px-2 u-py-2 | u-flex u-items-center u-justify-between u-gap-2">
              <div className="hero__item hero__item--start |  | u-flex  u-justify-center">
                <Login />
                {/* <Register /> */}
              </div>
              <div className="hero__item hero__item--end | u-flex u-flex-col  u-justify-center">
                <div className="form__group">
                  <p>Enter with guest account</p>
                </div>
                <div className="form__group">
                  <Link href="/tips">
                    <button className="btn | u-bg-secondary-200 | u-clr-white-0">
                      Guest
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
